apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: dev
  namespace: observability
spec:
  config:
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
      jaeger:
        protocols:
          thrift_binary: {}
          thrift_compact: {}
          thrift_http: {}
          grpc: {}

    processors:

    exporters:
      debug: {}
      otlp:
        endpoint: tempo-simplest-gateway.observability.svc.cluster.local:8090
        tls:
          insecure: false
          insecure_skip_verify: true
        headers:
          X-Scope-OrgID: demo

    service:
      pipelines:
        traces:
          receivers: [otlp, jaeger]
          exporters: [otlp]