apiVersion: v1
kind: Secret
metadata:
  name: tempo-s3
  namespace: observability
type: Opaque
stringData:
  # Tempo Operator expects these keys for S3 backends.
  access_key_id: "minio"
  access_key_secret: "minio12345"
  bucket: "tempo"
  endpoint: "http://minio.observability.svc.cluster.local:9000"
