apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: simplest
  namespace: observability
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  managementState: Managed
  replicationFactor: 1
  retention:
    global:
      traces: 24h
  storage:
    secret:
      name: tempo-s3-odf
      type: s3
  storageSize: 1Gi
  resources:
    total:
      limits:
        cpu: "1000m"
        memory: "2Gi"
  template:
    queryFrontend:
      jaegerQuery:
        enabled: true
        ingress:
          type: route
          route:
            termination: edge
  observability:
    metrics:
      createServiceMonitors: true
