apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: payment
  labels:
    app: payment
    app.openshift.io/runtime: camel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: image-registry.openshift-image-registry.svc:5000/payment/payment:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: QUARKUS_PROFILE
              value: demo