apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: payment
  labels:
    app: payment
spec:
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080