apiVersion: console.streamshub.github.com/v1alpha1
kind: Console
metadata:
  name: ticketblaster-console
  namespace: kafka-console
  finalizers:
    - consoles.console.streamshub.github.com/finalizer
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  hostname: ticketblaster-console.apps.cluster-rvwsv.rvwsv.sandbox3546.opentlc.com
  kafkaClusters:
    - name: demo-cluster
      namespace: kafka
      listener: plain

