apiVersion: noobaa.io/v1alpha1
kind: BackingStore
metadata:
  name: tempo-mcg-backingstore
  namespace: openshift-storage
  labels:
    app: noobaa
spec:
  type: pv-pool
  pvPool:
    numVolumes: 1
    storageClass: gp3-csi
    resources:
      requests:
        storage: 10Gi
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

