apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: order
  namespace: order
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: https://github.com/panchoraposo/camel-quarkus-saga.git
      ref: main
    contextDir: order
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: src/main/docker/Dockerfile.openshift
  output:
    to:
      kind: ImageStreamTag
      name: order:latest
  triggers:
    - type: ConfigChange

