apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: order
  namespace: order
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
      labels:
        app: order
        app.openshift.io/runtime: camel
    spec:
      containers:
        - image: quay.io/fraposo/order:0.2
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "100m"