apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: order
  namespace: order
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
      labels:
        app: order
        app.openshift.io/runtime: camel
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/order/order:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: QUARKUS_PROFILE
              value: demo
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "100m"
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/q/health/ready"
              port: 8080
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 3
