apiVersion: v1
kind: Service
metadata:
  name: order-metrics
  namespace: order
  labels:
    app: order
    ticketblaster.redhat.demo/component: metrics
spec:
  selector:
    serving.knative.dev/service: order
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
