apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: tempo-operatorgroup
  namespace: openshift-tempo-operator
spec:
  # Install cluster-wide (required by the Red Hat Tempo operator).
