apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  finalizers:
    - knative-serving-openshift
    - knativeservings.operator.knative.dev
  name: knative-serving
  namespace: knative-serving
spec:
  controller-custom-certs:
    name: ''
    type: ''
  registry: {}