apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  config:
    deployment:
      registriesSkippingTagResolving: "image-registry.openshift-image-registry.svc:5000"