apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: opentelemetry-operatorgroup
  namespace: openshift-opentelemetry-operator
spec:
  # Install cluster-wide (required by the Red Hat OpenTelemetry operator).