apiVersion: apps/v1
kind: Deployment
metadata:
  name: allocations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: allocations
  template:
    metadata:
      labels:
        app: allocations
    spec:
      containers:
        - name: allocations
          image: registry.redhat.io/rhel10/postgresql-16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRESQL_USER
              value: quarkus
            - name: POSTGRESQL_PASSWORD
              value: quarkus
            - name: POSTGRESQL_DATABASE
              value: allocations
          volumeMounts:
            - mountPath: /var/lib/pgsql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          emptyDir: {}