apiVersion: v1
kind: Service
metadata:
  name: allocation
  namespace: allocation
  labels:
    app: allocation
spec:
  selector:
    app: allocation
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080