apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: frontend
  namespace: frontend
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: https://github.com/panchoraposo/camel-quarkus-saga.git
      ref: main
    contextDir: frontend
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: frontend:latest
  triggers:
    - type: ConfigChange

