apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
    app.openshift.io/runtime: react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: order
          image: quay.io/fraposo/saga-frontend:0.2
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: frontend-config