apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - loki-odf-obc.yaml
  - loki-odf-s3-secret-job.yaml
  - lokistack.yaml
  - collector-rbac.yaml
  - clusterlogforwarder.yaml
