apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-logging-stack
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["*"]
  - apiGroups: ["loki.grafana.com"]
    resources: ["lokistacks"]
    verbs: ["*"]
  - apiGroups: ["observability.openshift.io"]
    resources: ["clusterlogforwarders"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["serviceaccounts", "secrets", "configmaps"]
    verbs: ["*"]
  - apiGroups: ["objectbucket.io"]
    resources: ["objectbucketclaims"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-logging-stack
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-logging-stack
