apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: frontend
  labels:
    app: frontend
data:
  REACT_APP_KEYCLOAK_REALM: "ticketblaster"
  REACT_APP_KEYCLOAK_CLIENT_ID: "frontend"
