apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend
  namespace: frontend
  labels:
    app: frontend
spec:
  to:
    kind: Service
    name: frontend
  port:
    targetPort: 3000
    
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect