apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-operator
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/panchoraposo/demo-camel-saga'
    targetRevision: HEAD
    path: operators/keycloak
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: keycloak
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

