apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-payment
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/panchoraposo/demo-camel-saga'
    targetRevision: HEAD
    path: apps/payment/overlays/dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: payment
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true