apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storagesystem
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/panchoraposo/demo-camel-saga'
    targetRevision: HEAD
    path: apps/odf/storage-system
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openshift-storage
  syncPolicy:
    automated:
      selfHeal: true
      prune: true